triggers:
- envs: []
  last_enabled_at: 2024-02-05 15:55:10.328376
  name: daily_run
  pipeline_uuid: green_taxi_etl
  schedule_interval: 0 5 * * *
  schedule_type: time
  settings:
    landing_time_enabled: false
  sla: null
  start_time: 2024-02-05 05:00:00
  status: active
  variables: {}
